# Flutter CD configuration file with Cloud build

steps:

# clone the latest source codes 
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Solution-Challenge/googreen.git']
  dir: '/workspace'
  timeout: 500s

  # using flutter builder Docker image we have built previously to compile the repo
- name: 'gcr.io/cloud-builders/flutter'
  entrypoint: '/bin/bash'
  args: ['build.sh', 'googreen']